import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
await fs.mkdir('.qa',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4321/',{waitUntil:'networkidle'});
await page.screenshot({path:'.qa/desktop.png',fullPage:true});
await page.locator('[data-topic="ai"]').click();
if(!await page.locator('#feed-ai').isVisible())throw Error('Feed failed to expand');
await page.locator('[data-topic="world"]').click();
if(await page.locator('#feed-ai').isVisible()||!await page.locator('#feed-world').isVisible())throw Error('Topic switching failed');
await page.keyboard.press('Escape');
if(await page.locator('#feed-world').isVisible())throw Error('Escape failed');
await page.locator('#theme-toggle').click();
await page.reload();
if(await page.locator('html').getAttribute('data-theme')!=='light')throw Error('Theme persistence failed');
await page.screenshot({path:'.qa/light.png',fullPage:true});
await page.goto('http://127.0.0.1:4321/tools/');
await page.locator('#tool-search').fill('MXToolbox');
if(await page.locator('[data-tool]:visible').count()!==1)throw Error('Tool search failed');
await page.locator('#tool-search').fill('not-a-tool');
if(!await page.locator('#no-tools').isVisible())throw Error('Empty search failed');
await page.locator('#tool-search').fill('');await page.locator('#tool-category').selectOption('Hardware');
if(await page.locator('[data-tool]:visible').count()!==3)throw Error('Category filter failed');
const routes=['/','/lab/','/life/','/advocacy/','/lab/ticket-goblin/','/links/','/comedy/','/tools/subnet-calculator/'];
for(const route of routes){const response=await page.goto('http://127.0.0.1:4321'+route);if(response.status()!==200)throw Error('Route failed: '+route);}
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:4321/');await page.locator('#theme-toggle').click();
await page.screenshot({path:'.qa/mobile.png',fullPage:true});
for(const route of routes){await page.goto('http://127.0.0.1:4321'+route);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile overflow '+route);}
await page.route('https://api.weather.gov/**',r=>r.abort());
await page.goto('http://127.0.0.1:4321/');await page.waitForFunction(()=>document.querySelector('#weather').textContent.includes('unavailable'));
await page.locator('[data-topic="safety"]').click();
if(!await page.locator('#feed-safety').innerText())throw Error('Feed failure message absent');
const noJS=await browser.newPage({javaScriptEnabled:false});await noJS.goto('http://127.0.0.1:4321/');if(!await noJS.locator('noscript').first().isVisible())throw Error('No JS fallback missing');
await fs.writeFile('.qa/browser-results.json',JSON.stringify({passed:true,routes,errors},null,2));
if(errors.length)throw Error(errors.join('\n'));console.log('Desktop/mobile, routes, topic controls, theme persistence, toolbox filters, weather failure, no-JS fallback: passed.');
await browser.close();
